### ISSUE TITLE
Mouse cursor moves opposite direction of the head in game

### ISSUE THREAD

**Issue by mangos12** [glenmurphy/fingers#14] opened 2023-06-07 01:18 UTC
First of all, I'd like to say thank you for your effort.

I found that Mouse cursor moves opposite direction of the head movement(both X and Y axis).
If I place my hand in front of my head and turn my head left, the cursor moves to the right.

It's understandable on the desktop because if I fix my hand location and move my head, the relative location changes.

However, default leap motion hand on DCS doesn't act like this.
If I hold my virtual hand in one position, it stays there even though I turn my head.
(All other apps are working correctly)

This is very uncomfortable, cursor is moving opposite directions with my head movement
makes me impossible to click anything at once. 
Tested FFR and up scaling off, changing window resolution to math the headset's ratio, all didn't work out so far.

I'm using a pimax hand tracking module with 5.12 driver(read as Leap motion IR 170 on my system).

Please give me an advice.
Thank you for your time.

**Comment by glenmurphy** [comment] 2023-06-07 02:01
Hi @mangos12 

The behavior you describe is sad, but expected to happen when you are in the DCS menu system because the DCS mouse works differently in that mode (DCS does not offset it relative to the head). Fingers should work properly when you are in the cockpit though - if you go to instant action and sit in the cockpit, does it still not work properly?

~ Glen

**Comment by mangos12** [comment] 2023-06-07 03:59
Thanks for the reply.

Yes, the issue remains even inside the cockpit. 
I've checked numerous videos on youtube and forums using Fingers, but couldn't find any case.

I've also tried different versions of your program, but no luck so far..

**Comment by glenmurphy** [comment] 2023-06-08 06:28
Can I double check what's happening, because the menus and cockpit should actually work in different ways. Sorry if I am not understanding properly.

When you are in the cockpit, if you put your hand so that the cursor is over something in the cockpit (e.g. the velocity indicator), when you turn your head slowly to the left does the cursor stay (roughly) over that cockpit element, move to the left (with the head) or move further away to the right? From what I can tell it is the last one, but I want to be sure.

**Comment by DavidHenricsson** [comment] 2023-08-11 20:54
I have the same issue, any fix for this?

**Comment by glenmurphy** [comment] 2023-10-29 03:57
With 2.9 I have been able to replicate this - the sensitivity does get too high sometimes. I could try to be clever about detecting it, but I think I will just add a sensitivity scale control

Thank you for your patience

**Comment by glenmurphy** [comment] 2023-10-29 09:50
Duplicate of #13

**Comment by glenmurphy** [comment] 2023-10-29 09:51
Duplicate of #12

**Closed** 2023-10-29 09:52 UTC

**Comment by glenmurphy** [comment] 2023-10-30 00:17
This should now be controllable in v0.9.5

**Comment by mangos12** [comment] 2023-11-28 08:22
Thank your very much for the update!
